//all values in ms
export const DELAY_BEFORE_YELLOW_GREEN = 5000;
export const DELAY_BEFORE_YELLOW_MAIN = 5000;
export const DELAY_BEFORE_YELLOW_RED_MAIN = 2000;
export const DELAY_GREEN_SIDE = 5000;
export const DELAY_BEFORE_GREEN_SIDE = 2000;
export const DELAY_BEFORE_YELLOW_RED_SIDE = 1000;
export const DELAY_BEFORE_YELLOW_SIDE = 1000;

//all values in ms
export const TOTAL_TRAFFIC_LIGHT_DURATION =
  DELAY_BEFORE_YELLOW_MAIN +
  DELAY_BEFORE_YELLOW_RED_SIDE +
  DELAY_BEFORE_GREEN_SIDE +
  DELAY_GREEN_SIDE +
  DELAY_BEFORE_YELLOW_SIDE +
  DELAY_BEFORE_YELLOW_RED_MAIN;
