export const DELAY_BEFORE_YELLOW_MAIN = 5000;
export const DELAY_BEFORE_YELLOW_RED_SIDE = 1000;
export const DELAY_BEFORE_GREEN_SIDE = 2000;
export const DELAY_GREEN_SIDE = 5000;
export const DELAY_BEFORE_YELLOW_SIDE = 1000;
export const DELAY_BEFORE_YELLOW_RED_MAIN = 2000;

export const TOTAL_TRAFFIC_LIGHT_DURATION =
  DELAY_BEFORE_YELLOW_MAIN +
  DELAY_BEFORE_YELLOW_RED_SIDE +
  DELAY_BEFORE_GREEN_SIDE +
  DELAY_GREEN_SIDE +
  DELAY_BEFORE_YELLOW_SIDE +
  DELAY_BEFORE_YELLOW_RED_MAIN;

export const actionTypes = {
  START_SYSTEM: "START_SYSTEM",
  SET_TRAFFIC_LIGHT_COLOR: "SET_TRAFFIC_LIGHT_COLOR",
  SET_PEDESTRIAN_LIGHT_RED: "SET_PEDESTRIAN_LIGHT_RED",
  SET_PEDESTRIAN_LIGHT_GREEN: "SET_PEDESTRIAN_LIGHT_GREEN",
  PEDESTRIAN_REQUEST_GREEN: "PEDESTRIAN_REQUEST_GREEN",
  SET_PEDESTRIAN_PHASE_ACTIVE: "SET_PEDESTRIAN_PHASE_ACTIVE",
  SET_PEDESTRIAN_PHASE_INACTIVE: "SET_PEDESTRIAN_PHASE_INACTIVE",
  REMOVE_PEDESTRIAN_FROM_QUEUE: "REMOVE_PEDESTRIAN_FROM_QUEUE",
};
